version: "3.9"

services:
  webhook:
    build: .
    container_name: gromit
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/gromit  # mount source for live editing
    command: sh -c "pip install --no-cache-dir -r requirements.txt && python app.py"
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
