"""added host_id ref

Revision ID: 9bfa0c89aa95
Revises: 4bd8597d152f
Create Date: 2025-10-02 21:35:56.506674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bfa0c89aa95'
down_revision = '4bd8597d152f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('host', schema=None) as batch_op:
        batch_op.add_column(sa.Column('port_number', sa.String(length=50), server_default='8060', nullable=False))
        batch_op.add_column(sa.Column('host_type_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_foreign_key("fk_host_host_type", 'host_type', ['host_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('host', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('host_type_id')
        batch_op.drop_column('port_number')

    # ### end Alembic commands ###
