"""changed host_id to nullable

Revision ID: a35fe6ba59d0
Revises: 6c75b7455fb9
Create Date: 2025-10-06 14:47:11.348009

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a35fe6ba59d0'
down_revision = '6c75b7455fb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variable', schema=None) as batch_op:
        batch_op.alter_column('host_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('variable', schema=None) as batch_op:
        batch_op.alter_column('host_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
