"""added host_app table

Revision ID: ed29b49fef7e
Revises: af4314302ef1
Create Date: 2025-10-02 23:25:27.482634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed29b49fef7e'
down_revision = 'af4314302ef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host_app',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gromit_app_name', sa.String(length=50), nullable=True),
    sa.Column('host_app_name', sa.String(length=50), nullable=False),
    sa.Column('host_app_id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['host.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('host_app')
    # ### end Alembic commands ###
